# Generated by Django 3.2.19 on 2023-06-24 06:35

import FruitipediaApp.fruitipedia.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), FruitipediaApp.fruitipedia.validators.validate_profile_names_start])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), FruitipediaApp.fruitipedia.validators.validate_profile_names_start])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
